apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
        - containerPort: 9001 # WS
        # - containerPort: 8883 # MQTTS
        volumeMounts:
        - mountPath: "/mosquitto/config/"
          name: config
        # - mountPath: "/mosquitto/certs/"
        #   name: certs
        - mountPath: "/mosquitto/data/"
          name: data
      volumes:
      - name: config
        configMap:
          name: mosquitto-config
      # - name: certs
      #   secret:
      #     secretName: mosquitto-certs
      - name: data
        persistentVolumeClaim:
          claimName: mosquitto-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |

    persistence true
    persistence_location /mosquitto/data/

    log_dest stdout

    # Enforce user authentication
    allow_anonymous false
    password_file /mosquitto/config/passwd

    # Default listener for direct MQTT traffic
    listener 1883
    protocol mqtt

    # Listener for MQTT traffic over Websockets
    listener 9001
    protocol websockets
  
  # Write down your user credentials generated with mosquitto_passwd here
  passwd: |
    example:$6$OlFZo8vTPy2xmhCv$s2HNta0sPPhbnSqAnsq43xiuc5c41nos4tIL6qagVkjG6THbYWVlSigkLkfbuUKufBmt9yM7MIQkCbiZCpix/w==

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtt
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
  - port: 1883
    nodePort: 30883
    name: mosquitto-mqtt
  - port: 9001
    nodePort: 30884
    name: mosquitto-ws
